# Deterministic Key Derivation (DKD) Basic Scenario

[metadata]
name = "dkd_basic_derivation"
description = "Basic P2P deterministic key derivation scenario"
version = "1.0.0"
author = "Aura Team"
tags = ["dkd", "key-derivation", "p2p", "core"]

[setup]
participants = 2
threshold = 2
seed = 42

[network]
latency_range = [40, 60]
drop_rate = 0.01

[[phases]]
name = "handshake"
description = "Establish secure communication channel"
timeout_seconds = 2
actions = [
    { type = "run_choreography", choreography = "handshake", participants = ["alice", "bob"] }
]

[[phases]]
name = "context_agreement"
description = "Agree on derivation context and parameters"
timeout_seconds = 2
actions = [
    { type = "run_choreography", choreography = "context_agreement", participants = ["alice", "bob"], app_id = "test_app_v1", context = "user_authentication" }
]

[[phases]]
name = "key_derivation"
description = "Perform collaborative key derivation"
timeout_seconds = 3
actions = [
    { type = "run_choreography", choreography = "p2p_dkd", participants = ["alice", "bob"], threshold = 2, app_id = "test_app_v1", context = "user_authentication" }
]

[[phases]]
name = "validation"
description = "Validate derived keys match"
timeout_seconds = 2
actions = [
    { type = "verify_property", property = "derived_keys_match", expected = true },
    { type = "verify_property", property = "derivation_deterministic", expected = true }
]

[[properties]]
name = "derived_keys_match"
property_type = "safety"

[[properties]]
name = "derivation_deterministic"
property_type = "safety"

[[properties]]
name = "no_key_leakage"
property_type = "safety"

[[properties]]
name = "derivation_completes"
property_type = "liveness"

