//! Identifier newtypes for MPST domains.

use serde::{Deserialize, Serialize};
use std::borrow::Cow;

/// Role identifier used by choreographic annotations.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct RoleId(String);

impl RoleId {
    /// Create a new role identifier.
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    /// Get the underlying role name.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<String> for RoleId {
    fn from(value: String) -> Self {
        Self::new(value)
    }
}

impl From<&str> for RoleId {
    fn from(value: &str) -> Self {
        Self::new(value)
    }
}

impl std::fmt::Display for RoleId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Message type identifier generated by choreography macros.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct MessageTypeId(Cow<'static, str>);

impl MessageTypeId {
    /// Create a new message type identifier from a static string.
    pub const fn new_static(value: &'static str) -> Self {
        Self(Cow::Borrowed(value))
    }

    /// Create a new message type identifier from an owned string.
    pub fn new(value: impl Into<String>) -> Self {
        Self(Cow::Owned(value.into()))
    }

    /// Get the underlying message type string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<String> for MessageTypeId {
    fn from(value: String) -> Self {
        Self::new(value)
    }
}

impl From<&str> for MessageTypeId {
    fn from(value: &str) -> Self {
        Self::new(value)
    }
}

impl std::fmt::Display for MessageTypeId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Non-empty role list used to enforce at least one role.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct NonEmptyRoleList<T>(Vec<T>);

impl<T> NonEmptyRoleList<T> {
    /// Create a non-empty list from head + tail.
    pub fn new(head: T, mut tail: Vec<T>) -> Self {
        let mut items = Vec::with_capacity(1 + tail.len());
        items.push(head);
        items.append(&mut tail);
        Self(items)
    }

    /// Try to create a non-empty list from a vector.
    pub fn from_vec(items: Vec<T>) -> Option<Self> {
        if items.is_empty() {
            None
        } else {
            Some(Self(items))
        }
    }

    /// Borrow items as a slice.
    pub fn as_slice(&self) -> &[T] {
        &self.0
    }

    /// Iterate over items.
    pub fn iter(&self) -> std::slice::Iter<'_, T> {
        self.0.iter()
    }

    /// Number of items.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Append a new item.
    pub fn push(&mut self, item: T) {
        self.0.push(item);
    }
}

impl<T: PartialEq> NonEmptyRoleList<T> {
    /// Check if an item exists in the list.
    pub fn contains(&self, item: &T) -> bool {
        self.0.contains(item)
    }
}

impl<T> From<NonEmptyRoleList<T>> for Vec<T> {
    fn from(value: NonEmptyRoleList<T>) -> Self {
        value.0
    }
}

/// Session type identifier for protocol instances.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct SessionTypeId(String);

impl SessionTypeId {
    /// Create a new session type identifier.
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    /// Get the underlying session type identifier.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<String> for SessionTypeId {
    fn from(value: String) -> Self {
        Self::new(value)
    }
}

impl From<&str> for SessionTypeId {
    fn from(value: &str) -> Self {
        Self::new(value)
    }
}

impl std::fmt::Display for SessionTypeId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}
