[package]
name = "aura-sim-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
# Internal crates
aura-console-types = { path = "../console-types" }
wasm_core = { path = "../wasm-core" }

# WASM and web APIs
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
  "console",
  "WebSocket",
  "MessageEvent",
  "CloseEvent",
  "ErrorEvent",
  "BinaryType",
  "Blob",
  "FileReader",
  "Window",
  "Document",
  "Location",
] }

# Async runtime for WASM
wasm-bindgen-futures = "0.4"
futures = "0.3"

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
serde-wasm-bindgen = "0.6"

# Error handling
thiserror = { workspace = true }
anyhow = { workspace = true }

# Logging for WASM
console_error_panic_hook = "0.1"
wee_alloc = "0.4"

# UUID support for WASM
uuid = { workspace = true, features = ["js"] }

[dependencies.getrandom]
version = "0.2"
features = ["js"]

[dev-dependencies]
wasm-bindgen-test = "0.3"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

# Note: Profile settings moved to workspace root Cargo.toml
