//! Central registry of domain fact type identifiers.
//!
//! This module centralizes fact type IDs to enable collision checks and
//! registry coverage validation in a single place.

use aura_authentication::AUTH_FACT_TYPE_ID;
use aura_authorization::WOT_FACT_TYPE_ID;
use aura_chat::CHAT_FACT_TYPE_ID;
use aura_invitation::INVITATION_FACT_TYPE_ID;
use aura_recovery::RECOVERY_FACT_TYPE_ID;
use aura_relational::{
    CONTACT_FACT_TYPE_ID, GUARDIAN_BINDING_DETAILS_FACT_TYPE_ID, GUARDIAN_REQUEST_FACT_TYPE_ID,
    RECOVERY_GRANT_DETAILS_FACT_TYPE_ID,
};
use aura_rendezvous::RENDEZVOUS_FACT_TYPE_ID;
use aura_signature::VERIFY_FACT_TYPE_ID;
use aura_social::facts::SOCIAL_FACT_TYPE_ID;
use aura_social::moderation::facts::{
    BLOCK_BAN_FACT_TYPE_ID, BLOCK_GRANT_STEWARD_FACT_TYPE_ID, BLOCK_KICK_FACT_TYPE_ID,
    BLOCK_MUTE_FACT_TYPE_ID, BLOCK_PIN_FACT_TYPE_ID, BLOCK_REVOKE_STEWARD_FACT_TYPE_ID,
    BLOCK_UNBAN_FACT_TYPE_ID, BLOCK_UNMUTE_FACT_TYPE_ID, BLOCK_UNPIN_FACT_TYPE_ID,
};
use aura_store::STORAGE_FACT_TYPE_ID;
use aura_transport::TRANSPORT_FACT_TYPE_ID;

pub const FACT_TYPE_IDS: &[&str] = &[
    AUTH_FACT_TYPE_ID,
    CHAT_FACT_TYPE_ID,
    INVITATION_FACT_TYPE_ID,
    CONTACT_FACT_TYPE_ID,
    GUARDIAN_REQUEST_FACT_TYPE_ID,
    GUARDIAN_BINDING_DETAILS_FACT_TYPE_ID,
    RECOVERY_GRANT_DETAILS_FACT_TYPE_ID,
    RENDEZVOUS_FACT_TYPE_ID,
    RECOVERY_FACT_TYPE_ID,
    SOCIAL_FACT_TYPE_ID,
    BLOCK_MUTE_FACT_TYPE_ID,
    BLOCK_UNMUTE_FACT_TYPE_ID,
    BLOCK_BAN_FACT_TYPE_ID,
    BLOCK_UNBAN_FACT_TYPE_ID,
    BLOCK_KICK_FACT_TYPE_ID,
    BLOCK_PIN_FACT_TYPE_ID,
    BLOCK_UNPIN_FACT_TYPE_ID,
    BLOCK_GRANT_STEWARD_FACT_TYPE_ID,
    BLOCK_REVOKE_STEWARD_FACT_TYPE_ID,
    WOT_FACT_TYPE_ID,
    VERIFY_FACT_TYPE_ID,
    STORAGE_FACT_TYPE_ID,
    TRANSPORT_FACT_TYPE_ID,
];
