# Continuous Group Key Agreement (CGKA) using BeeKEM protocol
[package]
name = "aura-cgka"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]

# Cryptography
ed25519-dalek = { workspace = true }
blake3 = { workspace = true }
rand = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
serde_cbor = { workspace = true }

# Async
tokio = { workspace = true }

# Utilities
uuid = { workspace = true }
time = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
hex = { workspace = true }

# Local dependencies
aura-journal = { path = "../journal" }
aura-crypto = { path = "../crypto" }

[dev-dependencies]
tokio-test = "0.4"