# Mock implementation of Keyhive capabilities and BeeKEM protocol
# TODO: Replace with real keyhive_core when available
[package]
name = "keyhive_core"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
authors = ["Aura Contributors"]
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.6", features = ["v4", "serde"] }
blake3 = "1.5"
hex = "0.4"
thiserror = "1.0"
ed25519-dalek = { version = "2.1", features = ["serde"] }