mod arch;
mod policy;
mod runtime_typed_lifecycle_bridge;
mod support;

use anyhow::{bail, Result};

pub fn run(name: &str, args: &[String]) -> Result<()> {
    match name {
        "arch" => arch::run(args),
        "browser-cache-lifecycle" => policy::run_browser_cache_lifecycle(),
        "browser-cache-owner" => policy::run_browser_cache_owner(),
        "browser-driver-contract-sync" => policy::run_browser_driver_contract_sync(),
        "browser-driver-types" => policy::run_browser_driver_types(),
        "browser-install" => policy::run_browser_install(),
        "browser-observation-contract" => policy::run_browser_observation_contract(),
        "browser-observation-recovery" => policy::run_browser_observation_recovery(),
        "browser-restart-boundary" => policy::run_browser_restart_boundary(),
        "browser-toolchain" => policy::run_browser_toolchain(),
        "biscuit-verifier-boundary" => policy::run_biscuit_verifier_boundary(),
        "harness-action-preconditions" => policy::run_harness_action_preconditions(),
        "harness-bridge-contract" => policy::run_harness_bridge_contract(),
        "harness-authoritative-fact-boundary" => policy::run_harness_authoritative_fact_boundary(),
        "harness-actor-vs-move-ownership" => policy::run_harness_actor_vs_move_ownership(),
        "harness-backend-contract" => policy::run_harness_backend_contract(),
        "harness-boundary-policy" => policy::run_harness_boundary_policy(),
        "harness-command-plane-boundary" => policy::run_harness_command_plane_boundary(),
        "harness-conformance-gate" => policy::run_harness_conformance_gate(),
        "harness-core-scenario-mechanics" => policy::run_harness_core_scenario_mechanics(),
        "harness-export-override-policy" => policy::run_harness_export_override_policy(),
        "harness-focus-selection-contract" => policy::run_harness_focus_selection_contract(),
        "harness-matrix-inventory" => policy::run_harness_matrix_inventory(),
        "harness-mode-allowlist" => policy::run_harness_mode_allowlist(),
        "harness-observation-determinism" => policy::run_harness_observation_determinism(),
        "harness-observation-surface" => policy::run_harness_observation_surface(),
        "harness-onboarding-contract" => policy::run_harness_onboarding_contract(),
        "harness-onboarding-publication" => policy::run_harness_onboarding_publication(),
        "harness-ownership-policy" => policy::run_harness_ownership_policy(),
        "harness-raw-backend-quarantine" => policy::run_harness_raw_backend_quarantine(),
        "harness-recovery-contract" => policy::run_harness_recovery_contract(),
        "harness-render-convergence" => policy::run_harness_render_convergence(),
        "harness-revision-contract" => policy::run_harness_revision_contract(),
        "harness-row-index-contract" => policy::run_harness_row_index_contract(),
        "harness-runtime-events-authoritative" => {
            policy::run_harness_runtime_events_authoritative()
        }
        "harness-scenario-config-boundary" => policy::run_harness_scenario_config_boundary(),
        "harness-scenario-inventory" => policy::run_harness_scenario_inventory(),
        "harness-scenario-legality" => policy::run_harness_scenario_legality(),
        "harness-scenario-shape-contract" => policy::run_harness_scenario_shape_contract(),
        "harness-settings-surface-contract" => policy::run_harness_settings_surface_contract(),
        "harness-shared-scenario-contract" => policy::run_harness_shared_scenario_contract(),
        "harness-semantic-primitive-contract" => policy::run_harness_semantic_primitive_contract(),
        "harness-trace-determinism" => policy::run_harness_trace_determinism(),
        "harness-typed-json-boundary" => policy::run_harness_typed_json_boundary(),
        "harness-typed-semantic-errors" => policy::run_harness_typed_semantic_errors(),
        "harness-ui-parity-contract" => policy::run_harness_ui_parity_contract(),
        "harness-ui-state-evented" => policy::run_harness_ui_state_evented(),
        "harness-wait-contract" => policy::run_harness_wait_contract(),
        "observed-layer-boundaries" => policy::run_observed_layer_boundaries(),
        "ownership-annotation-ratchet" => policy::run_ownership_annotation_ratchet(args),
        "ownership-category-declarations" => policy::run_ownership_category_declarations(),
        "ownership-capability-audit" => policy::run_ownership_capability_audit(),
        "ownership-policy" => policy::run_ownership_policy(),
        "ownership-workflow-tag-ratchet" => policy::run_ownership_workflow_tag_ratchet(),
        "ignored-test-count-ratchet" => policy::run_ignored_test_count_ratchet(),
        "invitation-legacy-fallback-boundary" => policy::run_invitation_legacy_fallback_boundary(),
        "privacy-tuning-gate" => policy::run_privacy_tuning_gate(),
        "privacy-legacy-sweep" => policy::run_privacy_legacy_sweep(),
        "privacy-runtime-locality" => policy::run_privacy_runtime_locality(),
        "protocol-choreo-wiring" => policy::run_protocol_choreo_wiring(),
        "protocol-compat" => policy::run_protocol_compat(args),
        "protocol-device-id-legacy" => policy::run_protocol_device_id_legacy(args),
        "protocol-device-enrollment-contract" => policy::run_protocol_device_enrollment_contract(),
        "remote-ingress-boundary" => policy::run_remote_ingress_boundary(),
        "raw-transport-send-boundary" => policy::run_raw_transport_send_boundary(),
        "runtime-bootstrap-guardrails" => policy::run_runtime_bootstrap_guardrails(),
        "runtime-typed-lifecycle-bridge" => runtime_typed_lifecycle_bridge::run(),
        "security-boundary-policy" => policy::run_security_boundary_policy(),
        "security-bypass-symbols" => policy::run_security_bypass_symbols(),
        "secret-field-wrappers" => policy::run_secret_field_wrappers(),
        "runtime-boundary-allowlist" => policy::run_runtime_boundary_allowlist(args),
        "runtime-error-boundary" => policy::run_runtime_error_boundary(),
        "runtime-shutdown-order" => policy::run_runtime_shutdown_order(),
        "service-registry-ownership" => policy::run_service_registry_ownership(),
        "service-surface-declarations" => policy::run_service_surface_declarations(),
        "shared-flow-metadata" => policy::run_shared_flow_metadata(),
        "shared-flow-policy" => policy::run_shared_flow_policy(),
        "shared-intent-flow" => policy::run_shared_intent_flow(),
        "shared-raw-quarantine" => policy::run_shared_raw_quarantine(),
        "shared-semantic-dedup" => policy::run_shared_semantic_dedup(),
        "testing-exception-boundary" => policy::run_testing_exception_boundary(),
        "tui-observation-channel" => policy::run_tui_observation_channel(),
        "tui-product-path" => policy::run_tui_product_path(),
        "tui-selection-contract" => policy::run_tui_selection_contract(),
        "tui-semantic-snapshot" => policy::run_tui_semantic_snapshot(),
        "user-flow-coverage" => policy::run_user_flow_coverage(),
        "user-flow-guidance-sync" => policy::run_user_flow_guidance_sync(),
        "user-flow-policy-guardrails" => policy::run_user_flow_policy_guardrails(),
        "verification-coverage" => policy::run_verification_coverage(),
        _ => bail!("unknown policy check: {name}"),
    }
}
