# Session Types for Choreographic Protocol Safety
[package]
name = "aura-session-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace crates - minimal dependencies to avoid cycles
aura-crypto = { path = "../crypto" }
aura-journal = { path = "../journal" }
aura-groups = { path = "../groups" }

# Cryptography
blake3 = { workspace = true }
frost-ed25519 = { workspace = true }
ed25519-dalek = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# Async
tokio = { workspace = true }
futures = { workspace = true }

# Utilities
uuid = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"