[package]
name = "session_types"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
# Essential external dependencies only - no internal crate dependencies to keep it minimal

# Core dependencies for session types and unified type system
aura-errors = { path = "../aura-errors" }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
tracing = "0.1"
time = { workspace = true }

# WASM compatibility
wasm-bindgen = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }

[features]
default = []
wasm = ["wasm-bindgen", "js-sys"]

[dev-dependencies]
tokio-test = "0.4"