# Pluggable transport layer with presence ticket enforcement
[package]
name = "aura-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace crates
aura-crypto = { path = "../crypto" }
aura-journal = { path = "../journal" }
# session_types removed during refactor - implementation moved to coordination
aura-coordination = { path = "../coordination" }

# Networking
reqwest = { workspace = true }
snow = { workspace = true }
async-trait = { workspace = true }

# Cryptography provided through aura-crypto

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
serde_cbor = { workspace = true }
bincode = { workspace = true }
toml = { workspace = true }

# Async
tokio = { workspace = true }
futures = { workspace = true }

# Utilities
uuid = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"
