name: Setup Nix
description: Install Nix with disk cleanup and caching

inputs:
  cache-name:
    description: Cache key suffix for Nix store
    required: false
    default: default

runs:
  using: composite
  steps:
    - name: Free disk space
      shell: bash
      run: |
        echo "=== Disk space before cleanup ==="
        df -h /

        # Remove large unused tools (gains ~30GB)
        sudo rm -rf /usr/share/dotnet              # ~6GB
        sudo rm -rf /usr/local/lib/android         # ~10GB
        sudo rm -rf /opt/ghc                       # ~2GB
        sudo rm -rf /opt/hostedtoolcache/CodeQL    # ~5GB
        sudo rm -rf /usr/local/share/boost         # ~1GB
        sudo rm -rf /usr/share/swift               # ~1GB
        sudo rm -rf /opt/hostedtoolcache/Python    # ~1GB
        sudo rm -rf /opt/hostedtoolcache/Ruby      # ~0.5GB
        sudo rm -rf /opt/hostedtoolcache/go        # ~1GB
        sudo rm -rf /opt/hostedtoolcache/node      # ~0.5GB

        # Additional large directories
        sudo rm -rf /usr/local/graalvm             # ~1GB
        sudo rm -rf /usr/local/.ghcup              # ~2GB
        sudo rm -rf /opt/microsoft                 # ~1GB
        sudo rm -rf /opt/pipx                      # ~0.5GB
        sudo rm -rf /usr/local/share/chromium      # ~0.5GB
        sudo rm -rf /usr/local/share/powershell    # ~0.5GB
        sudo rm -rf /usr/share/miniconda           # ~0.5GB
        sudo rm -rf /usr/share/az_*                # Azure CLI
        sudo rm -rf /opt/az                        # Azure tools

        # Clean package managers
        sudo docker image prune --all --force 2>/dev/null || true
        sudo apt-get clean 2>/dev/null || true
        sudo apt-get autoremove -y 2>/dev/null || true

        echo "=== Disk space after cleanup ==="
        df -h /

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          # Reduce disk usage
          keep-derivations = false
          keep-outputs = false

    - name: Cache Nix store
      uses: actions/cache@v4
      with:
        path: /nix/store
        key: ${{ runner.os }}-nix-${{ inputs.cache-name }}-${{ hashFiles('flake.lock') }}
        restore-keys: |
          ${{ runner.os }}-nix-${{ inputs.cache-name }}-
          ${{ runner.os }}-nix-

    - name: Garbage collect Nix store
      shell: bash
      run: |
        # Remove unreachable store paths to save space before/after caching
        nix-collect-garbage --delete-old || true
        echo "Disk space after Nix GC:"
        df -h /
