name: Setup Nix
description: Install Nix with disk cleanup and caching

inputs:
  cache-name:
    description: Cache key suffix for Nix store
    required: false
    default: default

runs:
  using: composite
  steps:
    - name: Free disk space
      shell: bash
      run: |
        echo "Disk space before cleanup:"
        df -h /
        # Remove large unused tools
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/share/boost /usr/share/swift
        sudo rm -rf /opt/hostedtoolcache/Python /opt/hostedtoolcache/Ruby /opt/hostedtoolcache/go /opt/hostedtoolcache/node
        # Clean Docker and apt
        sudo docker image prune --all --force || true
        sudo apt-get clean || true
        echo "Disk space after cleanup:"
        df -h /

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          # Reduce disk usage
          keep-derivations = false
          keep-outputs = false

    - name: Cache Nix store
      uses: actions/cache@v4
      with:
        path: /nix/store
        key: ${{ runner.os }}-nix-${{ inputs.cache-name }}-${{ hashFiles('flake.lock') }}
        restore-keys: |
          ${{ runner.os }}-nix-${{ inputs.cache-name }}-
          ${{ runner.os }}-nix-

    - name: Garbage collect Nix store
      shell: bash
      run: |
        # Remove unreachable store paths to save space before/after caching
        nix-collect-garbage --delete-old || true
        echo "Disk space after Nix GC:"
        df -h /
