[package]
name = "protocol-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "protocol_core"
path = "src/lib.rs"

[dependencies]
aura-types = { path = "../aura-types" }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
