# Group messaging and key agreement using BeeKEM protocol
[package]
name = "aura-groups"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]

# Internal crates
aura-errors = { path = "../aura-errors" }
aura-crypto = { path = "../crypto" }
aura-journal = { path = "../journal" }
keyhive_core = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
blake3 = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"
