[package]
name = "aura-db-test"
version = "0.1.0"
edition = "2021"
description = "Datafrog WASM test for Aura distributed database"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
datafrog = "2.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"

web-sys = { version = "0.3", features = [
  "console",
  "Window",
] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.6"

# Logging for WASM
tracing = "0.1"
tracing-wasm = "0.2"

# Debug helpers
console_error_panic_hook = { version = "0.1", optional = true }

[dependencies.getrandom]
version = "0.2"
features = ["js"]

[dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = ["console_error_panic_hook"]
